security:
    session_fixation_strategy: migrate
    role_hierarchy:
        ROLE_SUPER_ADMIN : [ROLE_ADMIN]
        ROLE_ADMIN:    [ROLE_CUSTOMER]
        ROLE_CUSTOMER:
        ROLE_USER:

    providers:
        main:
            entity: { class: CoreBundle\Entity\User, property: email }

    encoders:
        CoreBundle\Entity\User: sha512

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false
            anonymous: true

        secured_area:
            pattern: ^/admin
            form_login:
                login_path: _admin_login
                check_path: _security_check
                default_target_path: AdminBundle_home
                always_use_default_target_path: true
            logout:
                path: _admin_logout
                target: _admin_login
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path: _admin_login
                domain: ~

    access_control:
      - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /super_secured, roles: [ROLE_SUPER_ADMIN] }
      - { path: /secured, roles: [ROLE_ADMIN] }
      - { path: ^/admin, roles: [ROLE_CUSTOMER, ROLE_ADMIN, ROLE_SUPER_ADMIN]}